import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import data from "@/data/data";
import VirtualizedList from "@/components/virtualizedList/VirtualizedList";
import log from "@/utils/log";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  log({ dataLength: data.length });
  let content;

  if (data) {
    content = <VirtualizedList data={data} />;
  } else {
    content = <div>waiting for list...</div>;
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>{content}</div>
      </main>
    </>
  );
}
